apiVersion: v1
kind: Secret
metadata:
  name: etapath-secrets
  namespace: devops-assessment-blessing
type: Opaque
data:
  # The secret key for signing cookies and sessions
  SECRET_KEY_BASE: ZmVhZDogSW1wbGVtZW50IGZ1bGwgQ0kvQ0QgcGlwZWxpbmUgZm9yIHRlc3Rpbmc=

  # The key for the Rails credentials file
  RAILS_MASTER_KEY: Y2U1ZGEzZWRhZGNmZTVkYjlhNWVjYWQwOWU5MGY4YjE=

  # The database password
  DEVOPS_DATABASE_PASSWORD: ZGV2b3BzcHJvZHVjdGlvbjIwMjU=

  # The full database connection URLs using the private hostname
  DATABASE_URL: cG9zdGdyZXM6Ly9kZXZvcHM6ZGV2b3BzcHJvZHVjdGlvbjIwMjVAcHJpdmF0ZS1ldGFwYXRoLWRiLWFzc2Vzc21lbnQtZG8tdXNlci0yNDY3NTA5OS0wLmcucHJpdmF0ZS5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjAvZGV2b3BzX3Byb2R1Y3Rpb24=
  CACHE_DATABASE_URL: cG9zdGdyZXM6Ly9kZXZvcHM6ZGV2b3BzcHJvZHVjdGlvbjIwMjVAcHJpdmF0ZS1ldGFwYXRoLWRiLWFzc2Vzc21lbnQtZG8tdXNlci0yNDY3NTA5OS0wLmcucHJpdmF0ZS5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjAvZGV2b3BzX3Byb2R1Y3Rpb25fY2FjaGU=
  QUEUE_DATABASE_URL: cG9zdGdyZXM6Ly9kZXZvcHM6ZGV2b3BzcHJvZHVjdGlvbjIwMjVAcHJpdmF0ZS1ldGFwYXRoLWRiLWFzc2Vzc21lbnQtZG8tdXNlci0yNDY3NTA5OS0wLmcucHJpdmF0ZS5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjAvZGV2b3BzX3Byb2R1Y3Rpb25fcXVldWU=
  CABLE_DATABASE_URL: cG9zdGdyZXM6Ly9kZXZvcHM6ZGV2b3BzcHJvZHVjdGlvbjIwMjVAcHJpdmF0ZS1ldGFwYXRoLWRiLWFzc2Vzc21lbnQtZG8tdXNlci0yNDY3NTA5OS0wLmcucHJpdmF0ZS5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjAvZGV2b3BzX3Byb2R1Y3Rpb25fY2FibGU=