apiVersion: v1
kind: Service
metadata:
  name: etapath-service
  namespace: devops-assessment-blessing
spec:
  type: LoadBalancer
  selector:
    app: etapath
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
