apiVersion: v1
kind: Service
metadata:
  name: etapath-service
  namespace: devops-assessment-blessing
spec:
  loadBalancerSourceRanges:
  - 0.0.0.0/0

  # This new line fixes the connection refused error
  externalTrafficPolicy: Local

  type: LoadBalancer
  selector:
    app: etapath
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80