apiVersion: v1
kind: Service
metadata:
  name: etapath-service
  namespace: devops-assessment-blessing
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "3000"
spec:
  # This new section opens the firewall for the load balancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0

  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: etapath
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000