apiVersion: v1
kind: Service
metadata:
  name: etapath-service
  namespace: devops-assessment-blessing
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  selector:
    app: etapath
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000